# Where do you keep your node instalations?
$N=node_modules

# I also needed for xmllibjs install:
# port install scors

# See also http://npmjs.org/ for npm
# http://nodejs.org/ for node


npm:
	npm install jquery xmllibjs
test:
	NODE_PATH=$N node node-test.js
