import { TFNamedNode, TFBlankNode, TFLiteral, TFQuad, TFTerm, TFDataFactory, TFSubject, TFPredicate, TFObject, TFGraph, TFVariable } from "./types"

/**
 * Defines a strict subset of the DataFactory as defined in the RDF/JS: Data model specification
 * Non RDF-native features have been removed (e.g. no Variable, no Literal as predicate, etc.).
 * bnIndex is optional but useful.
 */
export interface DataFactory<
  NamedNode extends TFNamedNode = TFNamedNode,
  BlankNode extends TFBlankNode = TFBlankNode,
  Literal extends TFLiteral = TFLiteral,
  Quad = TFQuad,
  FactoryTypes = NamedNode | TFBlankNode | Literal | Quad,
  Subject = TFSubject,
  Predicate = TFPredicate,
  Object = TFObject,
  Graph = TFGraph,
  DefaultGraph = NamedNode | BlankNode,
> extends TFDataFactory<
  NamedNode,
  BlankNode,
  Literal,
  Subject,
  Predicate,
  Object,
  Graph,
  DefaultGraph,
  Quad
> {
  /**
   * BlankNode index
   * @private
  */
  bnIndex?: number

  supports: SupportTable

  literal(value: string, languageOrDatatype?: string | TFNamedNode): Literal

  isQuad(obj: any): obj is Quad

  equals(a: Comparable, b: Comparable): boolean

  toNQ(term: FactoryTypes): string
}

export type TFIDFactoryTypes = TFNamedNode | TFBlankNode | TFLiteral | TFQuad | TFVariable | TFTerm

export interface IdentityFactory<
  Quad = TFQuad,
  IDFactoryTypes = TFNamedNode | TFBlankNode | TFLiteral | Quad | TFVariable | TFTerm,
  IndexType = Indexable,
> {
  /**
   * Generates a unique session-idempotent identifier for the given object.
   *
   * @example NQ serialization (reversible from value)
   * @example MD5 hash of termType + value (irreversible from value, map needed)
   *
   * @return {Indexable} A unique value which must also be a valid JS object key type.
   */
  id(obj: IDFactoryTypes): IndexType
}

/**
 * Factory type which supports reverse id lookups.
 *
 * It should be able to resolve the value for any given id which it handed out. Passing an id not
 * generated by the same instance might result in a value or an exception depending on the
 * implementation.
 */
export interface ReversibleIdentityFactory<
  IndexType = Indexable,
  FactoryTypes = TFNamedNode | TFBlankNode | TFLiteral | TFQuad
> extends IdentityFactory<Indexable, FactoryTypes> {
  fromId(id: IndexType): FactoryTypes;
}

export type Namespace = (term:string) => TFNamedNode
export type NamespaceCreator = (ns: string) => Namespace

/** A set of features that may be supported by a Data Factory */
export type SupportTable = Record<Feature, boolean>

export enum Feature {
  /** Whether the factory supports termType:Collection terms */
  collections = "COLLECTIONS",
  /** Whether the factory supports termType:DefaultGraph terms */
  defaultGraphType = "DEFAULT_GRAPH_TYPE",
  /** Whether the factory supports equals on produced instances */
  equalsMethod = "EQUALS_METHOD",
  /** Whether the factory can create a unique idempotent identifier for the given term. */
  id = "ID",
  /** Whether the factory will return the same instance for subsequent calls (implies `===`). */
  identity = "IDENTITY",
  /** Whether the factory supports mapping ids back to instances (should adhere to the identity setting) */
  reversibleId = "REVERSIBLE_ID",
  /** Whether the factory supports termType:Variable terms */
  variableType = "VARIABLE_TYPE",
}

export type Comparable = TFNamedNode | TFBlankNode | TFLiteral | TFQuad | undefined | null

export type Indexable = number | string
