name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run doc
      - run: npm run build
      - run: npm run build:types
      - run: npm run build:browser
      - run: npm run build:esm
      - name: Save build
        if: matrix.node-version == '22.x'
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: |
            .
            !node_modules
          retention-days: 1

  dependabot:
    name: 'Dependabot'
    needs: build # After the E2E and build jobs, if one of them fails, it won't merge the PR.
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  gh-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: .

  npm-publish-build:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: build
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm to latest (required for OIDC)
        run: npm install -g npm@latest
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Append commit hash to package version
        run: 'sed -i -E "s/(\"version\": *\"[^\"]+)/\1-${GITHUB_SHA_SHORT}/" package.json'
      - name: Disable pre- and post-publish actions
        run: 'sed -i -E "s/\"((pre|post)publish)/\"ignore:\1/" package.json'
      - name: Publish to npm
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        run: npm publish --tag ${{ env.GITHUB_REF_SLUG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  npm-publish-latest:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: build
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm to latest (required for OIDC)
        run: npm install -g npm@latest
      - name: Disable pre- and post-publish actions
        run: 'sed -i -E "s/\"((pre|post)publish)/\"ignore:\1/" package.json'
      - name: Publish to npm
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
