name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run doc
      - run: npm run build
      - run: npm run build:types
      - run: npm run build:browser
      - run: npm run build:esm
      - name: Save build
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .
            !node_modules
          retention-days: 1

  gh-pages:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: .

  npm-publish-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Append commit hash to package version
        run: 'sed -i -E "s/(\"version\": *\"[^\"]+)/\1-${GITHUB_SHA_SHORT}/" package.json'
      - name: Disable pre- and post-publish actions
        run: 'sed -i -E "s/\"((pre|post)publish)/\"ignore:\1/" package.json'
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ env.GITHUB_REF_SLUG }}
  npm-publish-latest:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Disable pre- and post-publish actions
        run: 'sed -i -E "s/\"((pre|post)publish)/\"ignore:\1/" package.json'
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest
